import { Substance } from "../substance.model";
import { EFFECT } from "../effect.model";
import { SUBSTANCE } from "../substance.model";

const list = [
    {
      name: SUBSTANCE.ADDY,
      replaceEffects: {
        [EFFECT.EXPLOSIVE]: EFFECT.EUPHORIC,
        [EFFECT.FOGGY]: EFFECT.ENERGIZING,
        [EFFECT.GLOWING]: EFFECT.REFRESHING,
        [EFFECT.LONG_FACED]: EFFECT.ELECTRIFYING,
        [EFFECT.SEDATING]: EFFECT.GINGERITIS,
      },
    },
    {
      name: SUBSTANCE.BANANA,
      replaceEffects: {
        [EFFECT.CALMING]: EFFECT.SNEAKY,
        [EFFECT.CYCLOPEAN]: EFFECT.ENERGIZING,
        [EFFECT.DISORIENTING]: EFFECT.FOCUSED,
        [EFFECT.ENERGIZING]: EFFECT.THOUGHT_PROVOKING,
        [EFFECT.FOCUSED]: EFFECT.SEIZURE_INDUCING,
        [EFFECT.LONG_FACED]: EFFECT.REFRESHING,
        [EFFECT.PARANOIA]: EFFECT.JENNERISING,
        [EFFECT.SMELLY]: EFFECT.ANTI_GRAVITY,
        [EFFECT.TOXIC]: EFFECT.SMELLY,
      },
    },
    {
      name: SUBSTANCE.BATTERY,
      replaceEffects: {
        [EFFECT.CYCLOPEAN]: EFFECT.GLOWING,
        [EFFECT.ELECTRIFYING]: EFFECT.EUPHORIC,
        [EFFECT.EUPHORIC]: EFFECT.ZOMBIFYING,
        [EFFECT.LAXATIVE]: EFFECT.CALORIE_DENSE,
        [EFFECT.MUNCHIES]: EFFECT.TROPIC_THUNDER,
        [EFFECT.SHRINKING]: EFFECT.MUNCHIES,
      },
    },
    {
      name: SUBSTANCE.CHILI,
      replaceEffects: {
        [EFFECT.ANTI_GRAVITY]: EFFECT.TROPIC_THUNDER,
        [EFFECT.ATHLETIC]: EFFECT.EUPHORIC,
        [EFFECT.LAXATIVE]: EFFECT.LONG_FACED,
        [EFFECT.MUNCHIES]: EFFECT.TOXIC,
        [EFFECT.SHRINKING]: EFFECT.REFRESHING,
        [EFFECT.SNEAKY]: EFFECT.BRIGHT_EYED,
        [EFFECT.THOUGHT_PROVOKING]: EFFECT.FOCUSED,
      },
    },
    {
      name: SUBSTANCE.CUKE,
      replaceEffects: {
        [EFFECT.EUPHORIC]: EFFECT.LAXATIVE,
        [EFFECT.FOGGY]: EFFECT.CYCLOPEAN,
        [EFFECT.GINGERITIS]: EFFECT.THOUGHT_PROVOKING,
        [EFFECT.MUNCHIES]: EFFECT.ATHLETIC,
        [EFFECT.SLIPPERY]: EFFECT.MUNCHIES,
        [EFFECT.SNEAKY]: EFFECT.PARANOIA,
        [EFFECT.TOXIC]: EFFECT.EUPHORIC,
      },
    },
    {
      name: SUBSTANCE.DONUT,
      replaceEffects: {
        [EFFECT.ANTI_GRAVITY]: EFFECT.SLIPPERY,
        [EFFECT.BALDING]: EFFECT.SNEAKY,
        [EFFECT.CALORIE_DENSE]: EFFECT.EXPLOSIVE,
        [EFFECT.FOCUSED]: EFFECT.EUPHORIC,
        [EFFECT.JENNERISING]: EFFECT.GINGERITIS,
        [EFFECT.MUNCHIES]: EFFECT.CALMING,
        [EFFECT.SHRINKING]: EFFECT.ENERGIZING,
      },
    },
    {
      name: SUBSTANCE.ENERGY_DRINK,
      replaceEffects: {
        [EFFECT.DISORIENTING]: EFFECT.ELECTRIFYING,
        [EFFECT.EUPHORIC]: EFFECT.ENERGIZING,
        [EFFECT.FOCUSED]: EFFECT.SHRINKING,
        [EFFECT.FOGGY]: EFFECT.LAXATIVE,
        [EFFECT.GLOWING]: EFFECT.DISORIENTING,
        [EFFECT.SCHIZOPHRENIA]: EFFECT.BALDING,
        [EFFECT.SEDATING]: EFFECT.MUNCHIES,
        [EFFECT.SPICY]: EFFECT.EUPHORIC,
        [EFFECT.TROPIC_THUNDER]: EFFECT.SNEAKY,
      },
    },
    {
      name: SUBSTANCE.FLU_MEDICINE,
      replaceEffects: {
        [EFFECT.ATHLETIC]: EFFECT.MUNCHIES,
        [EFFECT.CALMING]: EFFECT.BRIGHT_EYED,
        [EFFECT.CYCLOPEAN]: EFFECT.FOGGY,
        [EFFECT.ELECTRIFYING]: EFFECT.REFRESHING,
        [EFFECT.EUPHORIC]: EFFECT.TOXIC,
        [EFFECT.FOCUSED]: EFFECT.CALMING,
        [EFFECT.LAXATIVE]: EFFECT.EUPHORIC,
        [EFFECT.MUNCHIES]: EFFECT.SLIPPERY,
        [EFFECT.SHRINKING]: EFFECT.PARANOIA,
        [EFFECT.THOUGHT_PROVOKING]: EFFECT.GINGERITIS,
      },
    },
    {
      name: SUBSTANCE.GASOLINE,
      replaceEffects: {
        [EFFECT.DISORIENTING]: EFFECT.GLOWING,
        [EFFECT.ELECTRIFYING]: EFFECT.DISORIENTING,
        [EFFECT.ENERGIZING]: EFFECT.EUPHORIC,
        [EFFECT.EUPHORIC]: EFFECT.SPICY,
        [EFFECT.GINGERITIS]: EFFECT.SMELLY,
        [EFFECT.JENNERISING]: EFFECT.SNEAKY,
        [EFFECT.LAXATIVE]: EFFECT.FOGGY,
        [EFFECT.MUNCHIES]: EFFECT.SEDATING,
        [EFFECT.PARANOIA]: EFFECT.CALMING,
        [EFFECT.SHRINKING]: EFFECT.FOCUSED,
        [EFFECT.SNEAKY]: EFFECT.TROPIC_THUNDER,
      },
    },
    {
      name: SUBSTANCE.HORSE_SEMEN,
      replaceEffects: {
        [EFFECT.ANTI_GRAVITY]: EFFECT.CALMING,
        [EFFECT.GINGERITIS]: EFFECT.REFRESHING,
        [EFFECT.SEIZURE_INDUCING]: EFFECT.ENERGIZING,
        [EFFECT.THOUGHT_PROVOKING]: EFFECT.ELECTRIFYING,
      },
    },
    {
      name: SUBSTANCE.IODINE,
      replaceEffects: {
        [EFFECT.CALMING]: EFFECT.BALDING,
        [EFFECT.CALORIE_DENSE]: EFFECT.GINGERITIS,
        [EFFECT.EUPHORIC]: EFFECT.SEIZURE_INDUCING,
        [EFFECT.FOGGY]: EFFECT.PARANOIA,
        [EFFECT.REFRESHING]: EFFECT.THOUGHT_PROVOKING,
        [EFFECT.TOXIC]: EFFECT.SNEAKY,
      },
    },
    {
      name: SUBSTANCE.MEGA_BEAN,
      replaceEffects: {
        [EFFECT.ATHLETIC]: EFFECT.LAXATIVE,
        [EFFECT.CALMING]: EFFECT.GLOWING,
        [EFFECT.ENERGIZING]: EFFECT.CYCLOPEAN,
        [EFFECT.FOCUSED]: EFFECT.DISORIENTING,
        [EFFECT.JENNERISING]: EFFECT.PARANOIA,
        [EFFECT.SEIZURE_INDUCING]: EFFECT.FOCUSED,
        [EFFECT.SHRINKING]: EFFECT.ELECTRIFYING,
        [EFFECT.SLIPPERY]: EFFECT.TOXIC,
        [EFFECT.SNEAKY]: EFFECT.CALMING,
        [EFFECT.THOUGHT_PROVOKING]: EFFECT.ENERGIZING,
      },
    },
    {
      name: SUBSTANCE.MOTOR_OIL,
      replaceEffects: {
        [EFFECT.ENERGIZING]: EFFECT.MUNCHIES,
        [EFFECT.EUPHORIC]: EFFECT.SEDATING,
        [EFFECT.FOGGY]: EFFECT.TOXIC,
        [EFFECT.MUNCHIES]: EFFECT.SCHIZOPHRENIA,
        [EFFECT.PARANOIA]: EFFECT.ANTI_GRAVITY,
      },
    },
    {
      name: SUBSTANCE.MOUTH_WASH,
      replaceEffects: {
        [EFFECT.CALMING]: EFFECT.ANTI_GRAVITY,
        [EFFECT.CALORIE_DENSE]: EFFECT.SNEAKY,
        [EFFECT.EXPLOSIVE]: EFFECT.SEDATING,
        [EFFECT.FOCUSED]: EFFECT.JENNERISING,
      },
    },
    {
      name: SUBSTANCE.PARACETAMOL,
      replaceEffects: {
        [EFFECT.CALMING]: EFFECT.SLIPPERY,
        [EFFECT.ELECTRIFYING]: EFFECT.ATHLETIC,
        [EFFECT.ENERGIZING]: EFFECT.PARANOIA,
        [EFFECT.FOCUSED]: EFFECT.GINGERITIS,
        [EFFECT.FOGGY]: EFFECT.CALMING,
        [EFFECT.GLOWING]: EFFECT.TOXIC,
        [EFFECT.MUNCHIES]: EFFECT.ANTI_GRAVITY,
        [EFFECT.PARANOIA]: EFFECT.BALDING,
        [EFFECT.SPICY]: EFFECT.BRIGHT_EYED,
        [EFFECT.TOXIC]: EFFECT.TROPIC_THUNDER,
      },
    },
    {
      name: SUBSTANCE.VIAGRA,
      replaceEffects: {
        [EFFECT.ATHLETIC]: EFFECT.SNEAKY,
        [EFFECT.DISORIENTING]: EFFECT.TOXIC,
        [EFFECT.EUPHORIC]: EFFECT.BRIGHT_EYED,
        [EFFECT.LAXATIVE]: EFFECT.CALMING,
        [EFFECT.SHRINKING]: EFFECT.GINGERITIS,
      },
    },
  ];



//   export const substances: Substance[] = list.map((substance) => {
//     return {
//         name: substance.name,
//         // effectReplaceMap: new Map<EFFECT, EFFECT>(Object.entries(substance.replaceEffects))
//     }
//   })